apiVersion: v1
kind: Service
metadata:
  name: mattermost-service
  namespace: mattermost
spec:
  selector:
    app: mattermost
  ports:
  - protocol: TCP
    port: 8065
    targetPort: 8065
  type: ClusterIP
