apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: mattermost
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            location / {
                proxy_pass http://mattermost-service.mattermost.svc.cluster.local:8065;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # CORS 설정 추가
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;
                add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;

                # OPTIONS 메서드에 대한 프리플라이트 요청 처리
                if ($request_method = 'OPTIONS') {
                    add_header 'Access-Control-Allow-Origin' '*' always;
                    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, DELETE, PUT' always;
                    add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
                    add_header 'Access-Control-Max-Age' 1728000;
                    add_header 'Content-Length' 0;
                    add_header 'Content-Type' 'text/plain; charset=utf-8';
                    return 204;
                }
            }
        }
    }