apiVersion: v1
kind: ConfigMap
metadata:
  name: mattermost-db-config
  namespace: mattermost
data:
  POSTGRESQL_HOSTNAME: "junkie-saas-rds-postgresql.cxs2e2qiwk1f.ap-northeast-2.rds.amazonaws.com"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_DATABASE: "mattermost"
  POSTGRESQL_USER: "mmuser"
