apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost
  namespace: mattermost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mattermost
  template:
    metadata:
      labels:
        app: mattermost
    spec:
      containers:
      - name: mattermost
        image: 214346124741.dkr.ecr.ap-northeast-2.amazonaws.com/cloudnexus/mattermost:34
        imagePullPolicy: Always
        ports:
        - containerPort: 8065
        envFrom:
        - configMapRef:
            name: mattermost-db-config
        - secretRef:
            name: mattermost-db-secret
        env:
        - name: POSTGRESQL_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: mattermost-db-config
              key: POSTGRESQL_HOSTNAME
        - name: POSTGRESQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mattermost-db-config
              key: POSTGRESQL_PORT
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mattermost-db-config
              key: POSTGRESQL_DATABASE
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              name: mattermost-db-config
              key: POSTGRESQL_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mattermost-db-secret
              key: POSTGRESQL_PASSWORD
